Traceback (most recent call last):
  File "/Users/JerryHan88/PycharmProjects/taxi_projects/information_boards/b_aggregated_analysis/b2_summary/b2_s2_hourly_statistics.py", line 198, in <module>
    run()
  File "/Users/JerryHan88/PycharmProjects/taxi_projects/information_boards/b_aggregated_analysis/b2_summary/b2_s2_hourly_statistics.py", line 25, in run
    assert False
AssertionError
